# Generated by Django 3.1 on 2020-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_service', '0002_auto_20200907_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags_text',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
