# Generated by Django 3.1 on 2020-09-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_service', '0003_question_tags_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
    ]
